// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorjWyoLsUwqnVBMYCd9PoOU3zIY8zZvk',
    appId: '1:497229873114:web:d6891ff40e29679ccdcae3',
    messagingSenderId: '497229873114',
    projectId: 'doctor-rent',
    authDomain: 'doctor-rent.firebaseapp.com',
    storageBucket: 'doctor-rent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKSpD9bCeYyeInJXP8HQ-Uo8BJ635b378',
    appId: '1:497229873114:android:ef2e557a8d1df391cdcae3',
    messagingSenderId: '497229873114',
    projectId: 'doctor-rent',
    storageBucket: 'doctor-rent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBawOH-IAwBWMOCmcwkYL49xoeLJDBCNqY',
    appId: '1:497229873114:ios:ec8b4d1e3fcea501cdcae3',
    messagingSenderId: '497229873114',
    projectId: 'doctor-rent',
    storageBucket: 'doctor-rent.appspot.com',
    iosClientId: '497229873114-ftq1mg7o7cv498ocofrfbnuqsjm91tcf.apps.googleusercontent.com',
    iosBundleId: 'com.example.doctors',
  );
}
